[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "talend-task"
version = "0.1.18dev0"
description = "CLI and Python API for running Talend Cloud jobs"
license = "MIT"
license-files = ["LICENSE"]
authors = [{name = "Corey Goldberg"}]
maintainers = [{name = "Corey Goldberg"}]
readme = "README.md"
requires-python = ">=3.10"
keywords = [
    "talend",
    "talend-cloud",
    "qlik",
    "etl",
    "pipeline",
    "cli",
    "api",
    "jobs",
    "automation",
]
classifiers = [
    "Environment :: Console",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

dependencies = [
    "python-dotenv==1.2.3",
    "requests==2.34.2",
    "rich==15.0.0",
]

[project.scripts]
talend_task = "talend_task.cli:main"

[project.urls]
homepage = "https://github.com/cgoldberg/talend-task"
source = "https://github.com/cgoldberg/talend-task"
download = "https://pypi.org/project/talend-task"

[dependency-groups]
dev = [
    "tox",
]
lint = [
    "ruff",
]
test = [
    "pytest",
]
validate = [
    "validate-pyproject[all]",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest]
addopts = ["-v"]
testpaths = ["tests"]

[tool.ruff]
line-length = 88
respect-gitignore = true
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN", "COM812", "D", "EM101", "EM102", "FBT",
    "PLR", "S101", "S105", "S106", "TRY003", "TRY400"
]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"**/test_*.py" = ["INP001", "SLF001"]

[tool.ruff.format]
docstring-code-line-length = 88
docstring-code-format = true
