# Tox (https://tox.wiki/) configuration file.
# To use it, run "tox" from this directory.
#
# For a specific environment, run:
#   "tox -e <env>" (i.e.: "tox -e lint")


[tox]
envlist =
    validate
    lint


[testenv:validate]
description = validate project configuration
dependency_groups =
    validate
commands =
    validate-pyproject pyproject.toml


[testenv:lint]
description = run linter and formatter
skip_install = true
dependency_groups =
    lint
commands =
    # run ruff for linting
    ruff check --fix --show-fixes --exit-non-zero-on-fix .
    # run ruff formatting
    ruff format --exit-non-zero-on-format .
