# Tox (https://tox.wiki/) configuration file.
# To use it, run "tox" from this directory.
#
# For a specific environment, run:
#     "tox -e <env>" (i.e.: "tox -e py314" or "tox -e lint")


[tox]
envlist =
    validate
    lint
    py310
    py314
skip_missing_interpreters = true


[testenv:validate]
description = validate project configuration and packaging
dependency_groups =
    validate
commands =
    validate-pyproject pyproject.toml
    python -c "from talend_task import TalendClient"
    talend_task -h


[testenv:lint]
description = run linter and formatter
skip_install = true
dependency_groups =
    lint
commands =
    # run ruff for linting
    ruff check --fix --show-fixes --exit-non-zero-on-fix .
    # run ruff formatting
    ruff format --exit-non-zero-on-format .


[testenv]
description = run tests
passenv = *
dependency_groups =
    test
commands =
    pytest {tty:--color=yes} {posargs:.}
