name: Build and Deploy API Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: pip install pdoc

      - name: Install package
        run: pip install -e .


      - name: Build API docs
        run: |
          REPO_URL="github.com/${{ github.repository }}"
          echo "Building docs..."
          pdoc talend_task \
            -o site \
            --no-search \
            --docformat markdown \
            --footer-text "${REPO_URL} (${GITHUB_SHA:0:7})"
          echo "Docs successfully built"

      - name: Publish API docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      - name: Show published URL
        run: |
          echo "Published API docs URL: https://coreygoldberg.com/talend-task"
          echo "GitHub commit: https://github.com/${{ github.repository }}/commit/${GITHUB_SHA}"
